### PR TITLE
Fix flaky tests

### LINKED ISSUE #658: Refactor remote sync test to provision remote cluster env test environment for each test

### PR DESCRIPTION
**Pull request by nesmabadr**
**Description**

Changes proposed in this pull request:

- Have a runtime cluster for each test

**Related issue(s)**
Resolves #658

### CODE REVIEW

File: controllers/control-plane/kcp_suite_test.go [hunk 1]
```diff
@@ -163,6 +162,5 @@ var _ = AfterSuite(func() {
 
 	err := controlPlaneEnv.Stop()
 	Expect(err).NotTo(HaveOccurred())
-	err = runtimeEnv.Stop()
-	Expect(err).NotTo(HaveOccurred())
+
```
Comment (medmes) [inline controllers/control-plane/kcp_suite_test.go:165]: All is well just this new line, could you please remove it? Many thanks for the fix!

**Review by medmes — CHANGES_REQUESTED** [review]

**Review by medmes — APPROVED** [review]
