### PR TITLE
fix: Update Manifest lastOperation when an error occurs

### LINKED ISSUE #1453: Manifest CR skip updating last operation when error occurs
### Description

At the moment, Manifest controller only update last operation field with some defined operations. However, for unexpected errors, KLM not record it, which makes troubleshooting sometimes difficult.

One example, the ssaStatusIfDiffExist not record the error while doing ssa to status subresources. 
https://github.com/kyma-project/lifecycle-manager/blob/36caa68020f6dd5c60913bb5fe0e803ffb244fb9/internal/declarative/v2/reconciler.go#L141-L148

### Steps to reproduce

we have one incident: #5371, the manifest CR requeued with error, but there is no lastOperation message indicating the error message.

### Environment Type

Managed

### Environment Info

Kubernetes Version: x.y.z
Docker Version: x.y.z
Kyma CLI Version: x.y.z
If used - k3d/k3s/minikube versions

### Actual Result
Last Operation in Manifest CR is not updated to reflect the error that occurred.

### Expected Result
Last Operation in Manifest CR should contain info on what was the last error.

### PR DESCRIPTION
**Pull request by nesmabadr**
**Description**

Changes proposed in this pull request:

- Update Manifest LastOperation when an error occurs

**Related issue(s)**
Resolves #1453

### CODE REVIEW

File: internal/declarative/v2/reconciler.go [hunk 1]
```diff
@@ -432,6 +433,7 @@ func (r *Reconciler) removeModuleCR(ctx context.Context, clnt Client, obj Object
 			if err := preDelete(ctx, clnt, r.Client, obj); err != nil {
 				r.Event(obj, "Warning", "PreDelete", err.Error())
 				// we do not set a status here since it will be deleting if timestamp is set.
```
Comment (Tomasz-Smelcerz-SAP) [inline internal/declarative/v2/reconciler.go:435]: Is this comment still valid?

File: internal/declarative/v2/reconciler.go [hunk 2]
```diff
@@ -514,9 +517,16 @@ func (r *Reconciler) pruneDiff(
...
 	manifest, ok := obj.(*v1beta2.Manifest)
 	if !ok {
+		obj.SetStatus(obj.GetStatus().WithErr(v1beta2.ErrTypeAssertManifest))
 		return v1beta2.ErrTypeAssertManifest
 	}
-	return resources.NewConcurrentCleanup(clnt, manifest).DeleteDiffResources(ctx, diff)
+	err = resources.NewConcurrentCleanup(clnt, manifest).DeleteDiffResources(ctx, diff)
+	if err != nil {
+		obj.SetStatus(obj.GetStatus().WithErr(err))
+		return err
```
Comment (Tomasz-Smelcerz-SAP) [inline internal/declarative/v2/reconciler.go:526]: You can save one line of code and move this return to the line 529 :)

File: internal/declarative/v2/reconciler.go (hunk 1 above)
Comment (nesmabadr) [reply internal/declarative/v2/reconciler.go:435]: yes because I don't set a new status, I only update the error with the current status

**Review by Tomasz-Smelcerz-SAP — APPROVED** [review]
