### PR TITLE
fix: Nil pointer when unmanaging module with `Ignore` CustomResourcePolicy

### LINKED ISSUE #2225: Nil Pointer Reference in Manifest Reconciler if
### Description

If a module has `customResourcePolicy = Ignore` and is set with the unmanaged annotation, the Manifest Reconciler will try to remove the managed-by on the defaultCR and the synced resources.

The defaultCR does not exist and causes a null pointer exception [here](https://github.com/kyma-project/lifecycle-manager/blob/3903f6aa36cfde59a12951727482e57cdeaf7132/internal/manifest/modulecr/client.go#L34).

### Steps to reproduce

Deploy template-operator with `customResourcePolicy: Ignore` and `managed: False`

### Environment Type

Managed

### AC

- [x] When `customResourcePolicy: Ignore`
  - [x] And `managed` is set to `False`
  - [x] Then no exception is thrown
- [x] Consider to add an e2e test overall testing the `customResourcePolicy: Ignore` case
   - [ ] if too extensive for this bug fix, create a follow-up ticket

### Environment Info

Kubernetes Version: x.y.z
Docker Version: x.y.z
modulectl Version: x.y.z
If used - k3d/k3s/minikube versions

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by c-pius**
**Description**

Changes proposed in this pull request:

- fixes the nil pointer exception
- refactors the label removal service
  - it should be e2e responsible for label removal from all objects
  - therefore, the check if needed for defaultCR and respective lookup moved from reconciler into the service
  - this way the removal can now be completely unit tested
- extends the unmanaging e2e test to include the case wehere CustomResourcePolicy is Ignore

**Related issue(s)**

- closes #2225

### CODE REVIEW

File: internal/manifest/labelsremoval/labels_removal.go [hunk 1]
```diff
@@ -54,19 +61,33 @@ func HandleLabelsRemovalFromResources(ctx context.Context, manifestCR *v1beta2.M
...
+	return nil
+}
+
+func removeFromDefaultCR(ctx context.Context,
+	manifest *v1beta2.Manifest,
+	skrClient client.Client,
+) error {
+	if manifest.Spec.Resource == nil {
 		return nil
 	}
```
Comment (c-pius) [inline internal/manifest/labelsremoval/labels_removal.go:78]: this will prevent the nil pointer

File: internal/manifest/modulecr/client.go [hunk 2]
```diff
@@ -30,6 +30,10 @@ func NewClient(client client.Client) *Client {
 func (c *Client) GetCR(ctx context.Context, manifest *v1beta2.Manifest) (*unstructured.Unstructured,
 	error,
 ) {
+	if manifest.Spec.Resource == nil {
+		return nil, nil
+	}
```
Comment (c-pius) [inline internal/manifest/modulecr/client.go:35]: Additional safety net in case somebody else starts using this

File: internal/manifest/modulecr/client.go [hunk 3]
```diff
@@ -30,6 +33,10 @@ func NewClient(client client.Client) *Client {
 func (c *Client) GetCR(ctx context.Context, manifest *v1beta2.Manifest) (*unstructured.Unstructured,
 	error,
 ) {
+	if manifest.Spec.Resource == nil {
+		return nil, ErrNoResourceDefined
+	}
```
Comment (c-pius) [inline internal/manifest/modulecr/client.go:38]: additional safety net in case somewhere else we start using this func

**Review by lindnerby — APPROVED** [review]
lgtm
