### PR TITLE
fix: make remote sync more resilient to missing resources and CRDs

### LINKED ISSUE #317: Remote Catalog Deletion for Dual Cluster Mode is breaking and causing infinite Deletion
When creating a Kyma, e.g.

```yaml
apiVersion: operator.kyma-project.io/v1alpha1
kind: Kyma
metadata:
  creationTimestamp: "2022-11-18T14:53:35Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2022-11-18T14:55:42Z"
  finalizers:
  - operator.kyma-project.io/Kyma
  generation: 3
  labels:
    kyma-project.io/broker-plan-id: xxx
    kyma-project.io/broker-plan-name: preview
    kyma-project.io/global-account-id: xxx
    kyma-project.io/instance-id: preview012
    kyma-project.io/runtime-id: xxx
    operator.kyma-project.io/kyma-name: xxx
    operator.kyma-project.io/managed-by: lifecycle-manager
  name: xxx
  namespace: kcp-system
  resourceVersion: "865370224"
  uid: 555d9cf4-e48d-45c3-a966-1c57716a5666
spec:
  channel: stable
  sync:
    enabled: true
    moduleCatalog: true
    namespace: kyma-system
    noModuleCopy: true
    strategy: secret
status:
  activeChannel: stable
  conditions:
  - lastTransitionTime: "2022-11-18T14:53:37Z"
    message: module catalog is synchronized
    observedGeneration: 2
    reason: ModuleCatalogIsReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-11-18T14:53:37Z"
    message: all modules are in ready state
    observedGeneration: 2
    reason: ModulesAreReady
    status: "True"
    type: Ready
  state: Deleting
```

The ModuleCatalog is attempted to be deleted but fails

```
 {"level":"ERROR","date":"2022-11-18T14:55:58.478592765Z","caller":"controller/controller.go:326","msg":"Reconciler error","context":{"controller":"kyma","controllerGroup":"operator.kyma-project.io","controllerKind":"Kyma","Kyma":{"name":"4d2102d6-fe81-4848-bfe4-9e399f62 │
│ 3d06","namespace":"kcp-system"},"namespace":"kcp-system","name":"4d2102d6-fe81-4848-bfe4-9e399f623d06","reconcileID":"f83afc10-145f-44ae-93a0-9f8037add77c","error":"could not delete remote module catalog: expected pointer, but got nil"},"stacktrace":"sigs.k8s.io/control │
│ ler-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/si │
│ gs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}     
````

This is causing deletion to be stuck infinetly.

AC:

- [ ] Deletion works properly
- [ ] Verified within a Control-Plane environment

### PR DESCRIPTION
**Pull request by jakobmoellersap**
Fixes #317

### CODE REVIEW

File: controllers/kyma_controller.go [hunk 1]
```diff
@@ -94,13 +98,23 @@ func (r *KymaReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.
 		return ctrl.Result{}, client.IgnoreNotFound(err) //nolint:wrapcheck
 	}
 
+	if kyma.Spec.Sync.Enabled {
+		var err error
```
Comment (ruanxin) [inline controllers/kyma_controller.go:102]: this `err` can be declared implicitly

File: controllers/kyma_controller.go [hunk 2]
```diff
@@ -146,60 +150,55 @@ func (r *KymaReconciler) CtrlErr(ctx context.Context, kyma *v1alpha1.Kyma, err e
...
+	syncContext.ReplaceWithVirtualKyma(controlPlaneKyma, remoteKyma)
 
 	return nil
 }
 
-func (r *KymaReconciler) syncModuleCatalog(ctx context.Context, syncContext *remote.KymaSynchronizationContext) error {
-	if !syncContext.ControlPlaneKyma.Spec.Sync.ModuleCatalog {
-		return nil
+func (r *KymaReconciler) syncModuleCatalog(ctx context.Context, kyma *v1alpha1.Kyma) (bool, error) {
+	if !kyma.Spec.Sync.Enabled || !kyma.Spec.Sync.ModuleCatalog {
```
Comment (ruanxin) [inline controllers/kyma_controller.go:171]: The issue of validating sync fields has been created here https://github.com/kyma-project/lifecycle-manager/issues/320

File: pkg/remote/context.go [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+import (
+	"context"
+	"errors"
+
+	"github.com/kyma-project/lifecycle-manager/api/v1alpha1"
+	"sigs.k8s.io/controller-runtime/pkg/client"
+)
+
+// syncContextKey is a singleton key.
+var syncContextKey = struct{}{} //nolint:gochecknoglobals
```
[the remark this answers is not in the document]
Comment (jakobmoellersap) [reply pkg/remote/context.go:12]: type declarations are not expressions and resolved during compile time. That means I cannot use a type as a key. However an empty struct is basically a 0 bytes pointer,

for reference try:

```go
var s struct{}
fmt.Println(unsafe.Sizeof(s)) // prints 0
```

File: controllers/kyma_controller.go (hunk 1 above)
Comment (ruanxin) [reply controllers/kyma_controller.go:102]: aha, got it. In this case, I think maybe it's better modify the `ctx` inside `InitializeSyncContext` directly instead of return it. But it's just an alternative, let's keep it this way.

**Review by ruanxin — APPROVED** [review]
