### PR TITLE
fix: Check all Module CRs across namespaces before deletion

### LINKED ISSUE #3006: KLM doesn't seem to consider Module CRs outside of the Default Module CRs namespace for safe deletion
### Description

In this ADR, it was aligned how KLM shall handle Module CRs as a gate before module deletion: https://github.com/kyma-project/community/issues/972. Specifically it reads in the consequences:

> For both CustomResourcePolicy: CreateAndDelete and CustomResourcePolicy: Ignore, lifecycle-manager uses ALL CRs of the Module CRD as the "gate" before proceeding with the deletion of the module. Lifecycle-manager does NOT report any configuration status of the module in the Kyma status.

However, it looks like the check implemented only checks for Module CRs part of namespace of the Default Module CR: https://github.com/kyma-project/lifecycle-manager/blob/a701253e856c4973eea0175cdc07f97a6fb7f4a9/internal/manifest/modulecr/client.go#L149-L156

This seems to be wrong and should be fixed.

### Steps to reproduce

- create test cluster on DEV
- enable telemetry module
- deploy a second Telemetry CR in default namespace
- remove the module from Kyma CR and observe if deletion is blocked or not
- if it is not blocked, then we have a problem

### Environment Type

Managed

### Environment Info

Kubernetes Version: x.y.z
Docker Version: x.y.z
modulectl Version: x.y.z
If used - k3d/k3s/minikube versions

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by medmes**
**Changes proposed in this pull request:**

 **Core fix:**
- Modified `GetAllModuleCRsExcludingDefaultCR` to search Module CRs across ALL namespaces using empty `ListOptions{}`
- Implemented `listResourcesByGroupKindInAllNamespaces` with `REST mapper` for API version compatibility
- Removed redundant namespace-specific function

**Testing:**
- Consolidated 4 similar e2e tests into single file with shared helper function `testModuleDeletionBlocking`
- Added unit test `TestClient_GetAllModuleCRsExcludingDefaultCR_WithCRsInDifferentNamespaces`])
- Test coverage: multiple CRs (same/cross-namespace) × policies (Ignore/CreateAndDelete)

**Code quality improvements:**
- Fixed test to create default CR in correct client for proper filtering validation
- Changed parameter from `GroupVersionKind` → `GroupKind` for semantic accuracy
- Reduced test code by ~60% (800+ → 285 lines) through consolidation

**Related issue:**
Fixes #3006

### CODE REVIEW

File: internal/manifest/modulecr/client.go [hunk 1]
```diff
@@ -211,6 +210,38 @@ func (c *Client) listResourcesByGroupKindInNamespace(ctx context.Context,
 	return allItems, nil
 }
 
+// listResourcesByGroupKindInAllNamespaces lists all resources matching the given GroupVersionKind
+// across ALL namespaces. This is required by ADR #972 to check all Module CRs before deletion.
+func (c *Client) listResourcesByGroupKindInAllNamespaces(ctx context.Context,
+	gvk schema.GroupVersionKind,
```
[the remark this answers is not in the document]
Comment (c-pius) [reply internal/manifest/modulecr/client.go]: The GroupKind can be retrieved from the moduleCR by `defaultModuleCR.GroupVersionKind().GroupKind()`

File: tests/e2e/module_deletion_blocking_test.go [hunk 2]
```diff
@@ -0,0 +1,284 @@
...
+
+		It("When remaining user-managed CRs are deleted", func() {
+			for _, cr := range userCRs[1:] {
+				Eventually(DeleteModuleCR).
+					WithContext(ctx).
+					WithArguments(cr.name, cr.namespace, skrClient).
+					Should(Succeed())
+			}
+		})
+	} else {
```
Comment (c-pius) [inline tests/e2e/module_deletion_blocking_test.go]: Better use a else if len == 1. Otherwise we may get hard to find problems when we misconfigure the test

File: tests/e2e/module_deletion_blocking_test.go [hunk 3]
```diff
@@ -0,0 +1,332 @@
...
+			moduleCR := &unstructured.Unstructured{}
+			moduleCR.SetGroupVersionKind(schema.GroupVersionKind{
+				Group:   templatev1alpha1.GroupVersion.Group,
+				Version: templatev1alpha1.GroupVersion.Version,
+				Kind:    string(templatev1alpha1.SampleKind),
+			})
+			Expect(skrClient.Get(ctx, defaultCRNamespacedName, moduleCR)).To(Succeed())
+			Expect(AddFinalizerToModuleCR(ctx, skrClient, moduleCR, "test-finalizer")).To(Succeed())
+		})
+	} else if len(userCreatedCRs) > 0 {
```
Comment (c-pius) [inline tests/e2e/module_deletion_blocking_test.go]: I don't understand why this is an `else if` rather then a separate `if`. Can you elaborate?
