### PR TITLE
fix: Deleting State Overwrite in Manifest Reconciler

### LINKED ISSUE #868: Module state is not propagated correctly to Kyma CR
**Description**
After the changes done [here](https://github.com/kyma-project/telemetry-manager/pull/405), if the user attempts to delete the Telemetry module while some custom resources related to Telemetry still exist in the cluster, the module deletion is blocked and the state of the Telemetry module will change to `Warning` . However, the Kyma CR shows that the Telemetry module is in `Deleting` state instead of the actual `Warning` state.

Also, the `Processing` state was removed [here](https://github.com/kyma-project/telemetry-manager/pull/333) and initially the Telemetry module state is empty. However, the Kyma CR shows that the Telemetry module is in `Processing` state.

**Expected result**
When Telemetry module is in `Warning` state, it is expected that the Telemetry state in Kyma CR is also `Warning`
```
  modules:
  - channel: fast
    fqdn: kyma-project.io/module/telemetry
    manifest:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Manifest
      metadata:
        generation: 1
        name: default-kyma-telemetry-812080235
        namespace: kyma-system
    name: telemetry
    resource:
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Telemetry
      metadata:
        name: default
        namespace: kyma-system
    state: Warning
```

When the state of the Telemetry module is empty, it is expected that the Telemetry state in Kyma CR is also empty
```
  modules:
  - channel: fast
    fqdn: kyma-project.io/module/telemetry
    manifest:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Manifest
      metadata:
        generation: 1
        name: default-kyma-telemetry-812080235
        namespace: kyma-system
    name: telemetry
    resource:
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Telemetry
      metadata:
        name: default
        namespace: kyma-system
    state: ""
```
**Actual result**
When Telemetry module is in `Warning` state, the Telemetry state in Kyma CR is incorrectly set as `Deleting`
```
kubectl get telemetry -n kyma-system
NAME      GENERATION   AGE   STATE
default   3            47m   Warning
```

```
  modules:
  - channel: fast
    fqdn: kyma-project.io/module/telemetry
    manifest:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Manifest
      metadata:
        generation: 1
        name: default-kyma-telemetry-812080235
        namespace: kyma-system
    name: telemetry
    resource:
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Telemetry
      metadata:
        name: default
        namespace: kyma-system
    state: Deleting
```

When the state of the Telemetry module is empty, the Telemetry state in Kyma CR is incorrectly set as `Processing`
```
kubectl get telemetry -n kyma-system default
NAME      GENERATION   AGE   STATE
default   1            16s
```

```
  modules:
  - channel: fast
    fqdn: kyma-project.io/module/telemetry
    manifest:
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Manifest
      metadata:
        generation: 1
        name: default-kyma-telemetry-812080235
        namespace: kyma-system
    name: telemetry
    resource:
      apiVersion: operator.kyma-project.io/v1alpha1
      kind: Telemetry
      metadata:
        name: default
        namespace: kyma-system
    state: Processing
```

**Steps to reproduce**
For reproducing that the `Warning` state of Telemetry module is not propagated to Kyma CR:

1. kyma provision k3d
2. kyma alpha deploy
3. kubectl apply -f moduletemplate.yaml
4. kyma alpha enable module telemetry -c fast
5. Create a sample LogPipeline: kubectl apply -f https://raw.githubusercontent.com/kyma-project/telemetry-manager/main/config/samples/telemetry_v1alpha1_logpipeline.yaml
6. kyma alpha disable module telemetry
7. Check Telemetry state in Telemetry CR (it will be `Warning`):  kubectl get telemetry -n kyma-system
8. Check Telemetry state in Kyma CR (it will be `Deleting`): kubectl get kyma -n kyma-system default-kyma -o yaml

For reproducing that the empty state of Telemetry module is not propagated to Kyma CR:
1. kyma provision k3d
2. kyma alpha deploy
3. kubectl apply -f moduletemplate.yaml
4. kyma alpha enable module telemetry -c fast
5. Initially before the module is ready, you will observe that Telemetry state in Telemetry CR is empty while Telemetry state in Kyma CR is `Processing`

**NOTE**: The changes [here](https://github.com/kyma-project/telemetry-manager/pull/405) are not released yet. So, you can use the below moduletemplate.yaml for debugging:
```
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleTemplate
metadata:
  name: telemetry-fast
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/module-name": "telemetry"
  annotations:
    "operator.kyma-project.io/doc-url": "https://kyma-project.io/#/telemetry-manager/user/README"
    "operator.kyma-project.io/is-cluster-scoped": "false" 
spec:
  channel: fast
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Telemetry
    metadata:
      labels:
        app.kubernetes.io/name: telemetry
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: telemetry-operator
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/created-by: telemetry-operator
      name: default
  descriptor:
    component:
      componentReferences: []
      labels:
      - name: security.kyma-project.io/scan
        value: enabled
        version: v1
      name: kyma-project.io/module/telemetry
      provider: internal
      repositoryContexts:
      - baseUrl: europe-west3-docker.pkg.dev/sap-kyma-huskies-dev/telemetry-module
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:226f793665a6c87a30099119bb170694370df21baca4c51f3b44f02a12e5b235
          type: localOciBlob
        name: raw-manifest
        relation: local
        type: yaml
        version: 1.0.0
      - access:
          imageReference: europe-docker.pkg.dev/kyma-project/prod/telemetry-manager:v20230911-69866791
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: telemetry-manager
        relation: external
        type: ociImage
        version: v20230911-69866791
      - access:
          imageReference: europe-docker.pkg.dev/kyma-project/prod/tpi/otel-collector:0.83.0-da21e9f9
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: otel-collector
        relation: external
        type: ociImage
        version: 0.83.0-da21e9f9
      - access:
          imageReference: europe-docker.pkg.dev/kyma-project/prod/tpi/fluent-bit:2.1.8-da21e9f9
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: fluent-bit
        relation: external
        type: ociImage
        version: 2.1.8-da21e9f9
      - access:
          imageReference: europe-docker.pkg.dev/kyma-project/prod/directory-size-exporter:v20230824-2d68935f
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: directory-size-exporter
        relation: external
        type: ociImage
        version: v20230824-2d68935f
      sources:
      - access:
          commit: 74293a3c9d884095fe9b4e09ab2d7045712463ed
          repoUrl: https://github.com/kyma-project/telemetry-manager
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: refs/heads/main
          version: v1
        - name: scan.security.kyma-project.io/language
          value: golang-mod
          version: v1
        - name: scan.security.kyma-project.io/subprojects
          value: "false"
          version: v1
        - name: scan.security.kyma-project.io/exclude
          value: '**/test/**,**/*_test.go'
          version: v1
        name: module-sources
        type: git
        version: 1.0.0
      version: 1.0.0
    meta:
      schemaVersion: v2
```

### PR DESCRIPTION
**Pull request by LeelaChacha**
Closes #868

### CODE REVIEW

File: tests/e2e_test/status_propagation_test.go [hunk 1]
```diff
@@ -53,6 +53,33 @@ var _ = Describe("Warning Status Propagation", Ordered, func() {
...
+	It("Should propagate Warning state even after marked for deletion", func() {
+		By("Getting manifest object key")
+		manifestObjectKey, err := GetManifestObjectKey(ctx, controlPlaneClient,
+			kyma.GetName(), "template-operator")
+		Expect(err).To(Not(HaveOccurred()))
+		By("Adding finalizer to avoid deletion")
+		err = AddFinalizerToManifest(ctx, manifestObjectKey, controlPlaneClient, "e2e-finalizer")
+		Expect(err).To(Not(HaveOccurred()))
+
+		By("Mark Manifest for deletion")
```
Comment (ruanxin) [inline tests/e2e_test/status_propagation_test.go:65]: The test scenario should be like this:
1. add finalizer to template operator defaultCR - `Sample`
2. disable template operator module in kyma 
   - it will trigger deletion for manifest CR
4. observe manifest CR under deleting and have state `Warning`

You should not add finalizer to manifest CR, manifest CR anyway pending for deletion if defaultCR is stuck under delete.

**Review by ruanxin — CHANGES_REQUESTED** [review]
test scenario is not correct.

File: tests/e2e_test/status_propagation_test.go [hunk 2]
```diff
@@ -53,12 +54,44 @@ var _ = Describe("Warning Status Propagation", Ordered, func() {
 			Should(Succeed())
 	})
 
-	It("Should disable Template Operator and Kyma should result in Ready status", func() {
+	It("Should propagate Warning state even after resource is marked for deletion", func() {
```
Comment (ruanxin) [inline tests/e2e_test/status_propagation_test.go:57]: Please don't modify the existing test case, the existing one verifies disable template operator module in a normal scenario, but your test is different. Write it as a dedicated one, you just need to enable the module again.

File: tests/e2e_test/utils_test.go [hunk 3]
```diff
@@ -202,3 +230,108 @@ func GetKymaStateMetricCount(ctx context.Context, kymaName, state string) (int,
 
 	return 0, nil
 }
+
+func GetManifestObjectKey(ctx context.Context, k8sClient client.Client, kymaName, templateName string) (
```
Comment (ruanxin) [inline tests/e2e_test/utils_test.go:234]: you can get manifest CR and resource CR information under `kyma.spec.status.modules`

an example:
```
manifest:
      apiVersion: [operator.kyma-project.io/v1beta2](http://operator.kyma-project.io/v1beta2)
      kind: Manifest
      metadata:
        generation: 5
        name: 31902256-3586-4a02-8e79-80c24c23c690-btp-operator-4128321918
        namespace: kcp-system
    name: btp-operator
    resource:
      apiVersion: [operator.kyma-project.io/v1alpha1](http://operator.kyma-project.io/v1alpha1)
      kind: BtpOperator
      metadata:
        name: btpoperator
        namespace: kyma-system
```

File: tests/e2e_test/utils_test.go [hunk 4]
```diff
@@ -202,3 +230,108 @@ func GetKymaStateMetricCount(ctx context.Context, kymaName, state string) (int,
...
+	}
+	return types.NamespacedName{Namespace: namespace, Name: name}, err
+}
+
+func AddFinalizerToSampleResource(ctx context.Context,
+	objKey types.NamespacedName,
+	k8sClient client.Client,
+	finalizer string,
+) error {
+	resource := &templateOperator.Sample{}
```
Comment (ruanxin) [inline tests/e2e_test/utils_test.go:276]: you don't need to use this typed `&templateOperator.Sample{}`, instead, use `Unstructured{}`, then you can avoid introducing template operator as a dependency.

File: go.mod [hunk 5]
```diff
@@ -32,6 +32,7 @@ require (
 )
 
 require (
+	github.com/kyma-project/template-operator v0.0.0-20230925081606-4ae25406be03
```
Comment (ruanxin) [inline go.mod:35]: we should not introduce template operator as dependency, it's not necessary.

File: tests/e2e_test/status_propagation_test.go [hunk 6]
```diff
@@ -53,12 +54,44 @@ var _ = Describe("Warning Status Propagation", Ordered, func() {
...
+			WithArguments(kyma.GetName(), kyma.GetNamespace(), controlPlaneClient,
+				"template-operator", v1beta2.StateWarning).
+			Should(Succeed())
+
+		By("Remove finalizer")
+		err = RemoveFinalizerToSampleResource(ctx, resourceObjectKey, controlPlaneClient, "e2e-finalizer")
+		Expect(err).To(Not(HaveOccurred()))
+	})
+
+	It("Kyma should result in Ready status", func() {
```
Comment (ruanxin) [inline tests/e2e_test/status_propagation_test.go:94]: after remove finalizer, kyma should result in Ready status. They should put in the same `It` spec, but not separate one.

File: tests/e2e_test/status_propagation_test.go [hunk 7]
```diff
@@ -53,12 +54,44 @@ var _ = Describe("Warning Status Propagation", Ordered, func() {
...
+			Should(Succeed())
+
 		By("Disabling Template Operator")
 		Eventually(DisableModule).
 			WithContext(ctx).
 			WithArguments(defaultRemoteKymaName, remoteNamespace, "template-operator", runtimeClient).
 			Should(Succeed())
+
+		By("Checking manifest state")
+		Eventually(CheckManifestIsInState).
```
Comment (ruanxin) [inline tests/e2e_test/status_propagation_test.go:78]: The manifest CR under deleting is not checked, you need to verify manifest CR DeletionTimestamp is not zero

File: tests/e2e_test/status_propagation_test.go [hunk 8]
```diff
@@ -81,3 +82,106 @@ var _ = Describe("Warning Status Propagation", Ordered, func() {
 			Should(Succeed())
 	})
 })
+
+var _ = Describe("Warning Status Propagation After When Deletion Timestamp Not Zero", Ordered, func() {
```
Comment (ruanxin) [inline tests/e2e_test/status_propagation_test.go:86]: This test need to write in new test file, then configured in github action as a dedicated test case.

So the workflow of e2e test is:
1. Github action will run each e2e separately, which means
2. it provisions e2e test infrastructure separately
3. it run `make -C tests/e2e_test ${{ matrix.e2e-test }}` in the end to trigger a dedicate test

Because of this, each e2e test are completely isolated, even not share same infrastructure, but for this, we need to put it in a dedicated file, and define it in `Makefile` as a new test target. 

But if you put your test as a different `Describe` in an existing test, you need to make sure the test case you designed will not influenced by other tests (they run in parallel). In your case, you need to `enable Template Operator `, which is also defined in `Warning Status Propagation` test, both of them will deploy template operator in a same skr cluster, which brings inconsistency.

File: tests/e2e_test/utils_test.go [hunk 9]
```diff
@@ -102,6 +113,39 @@ func CheckKymaIsInState(ctx context.Context,
...
+func CheckManifestDeletionTimestamp(ctx context.Context,
+	manifestObjKey types.NamespacedName,
+	k8sClient client.Client,
+	expectedTimestampZero bool,
+) error {
+	manifest := &v1beta2.Manifest{}
+	if err := k8sClient.Get(ctx, manifestObjKey, manifest); err != nil {
+		return err
+	}
+	GinkgoWriter.Printf("manifest %v\n", manifest)
```
Comment (ruanxin) [inline tests/e2e_test/utils_test.go:142]: this `GinkgoWriter` is just adding some debug information, please don't introduce them further. If the test fails, it's anyway will print out enough information for debug.

**Review by ruanxin — APPROVED** [review]

File: tests/e2e_test/deletion_status_propagation_test.go [hunk 10]
```diff
@@ -0,0 +1,85 @@
...
+		v1beta2.SyncStrategyLocalSecret)
+
+	InitEmptyKymaBeforeAll(kyma)
+	CleanupKymaAfterAll(kyma)
+
+	BeforeAll(func() {
+		// make sure we can list Kymas to ensure CRDs have been installed
+		err := controlPlaneClient.List(ctx, &v1beta2.KymaList{})
+		Expect(meta.IsNoMatchError(err)).To(BeFalse())
+	})
```
Comment (ruanxin) [inline tests/e2e_test/deletion_status_propagation_test.go:26]: we don't need this beforeall, not necessary, you can remove this part in other tasks as a refactoring purpose.

**Comment by ruanxin** [comment]
# Notes
I closed this PR by mistake, the code changes [here](https://github.com/kyma-project/lifecycle-manager/pull/923/files#diff-45632cfa5b5d235890e597e29448382f7c61fc85a55d1629de012328056e69a2L204) will break put manifest CR into deleting state.

The implementation of this PR is not done properly, @LeelaChacha if you need further clarification, feel free to reach me.

**Comment by ruanxin** [comment]
follow up PR https://github.com/kyma-project/lifecycle-manager/pull/956
